Jfhector 2.1.1. fix
alphagov/wcag-primer pull request #72
Opened 2021-07-21 16:59 UTC by chris-gds

What

Update docs via related PR: https://github.com/alphagov/wcag-primer/pull/34

2021-07-21 17:00 UTC, chris-gds reviewed
@owenatgov any chance you can approve and merge. This was rebased against the original

2021-07-22 14:59 UTC, maxgds requested changes
Looks good apart from one minor point I've commented on.

2021-07-22 14:59 UTC, maxgds commented on source/documentation/index.md
> +* 2.1.2 Make sure that keyboard users don't get stuck when navigating through content. [More about 2.1.2](/all.html#2-1-2-no-keyboard-trap-a)
GOV.UK style is to not use negative contractions so I think this should stay as "do not"

2021-07-27 07:36 UTC, maxgds approved these changes

2021-07-28 08:22 UTC, merged